tap "apple/apple", "http://github.com/apple/homebrew-apple"
tap "homebrew/bundle"
brew "apple/apple/game-porting-toolkit"
cask "r"
vscode "akamud.vscode-theme-onedark"
vscode "ms-azuretools.vscode-docker"
vscode "pdconsec.vscode-print"
